include=/home/kas/.config/foot/colors.ini

[main]
font=ZedMono Nerd Font:size=14
dpi-aware=yes
#line-height=<font metrics>
term=foot
font-size-adjustment=1
box-drawings-uses-font-glyphs=yes
bold-text-in-bright=yes

[url]
osc8-underline=always

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[scrollback] 
lines=10000
indicator-position=relative
indicator-format=- %p -

[key-bindings]
scrollback-up-page=Control+Shift+u
scrollback-down-page=Control+Shift+d
scrollback-up-line=Control+Shift+k
scrollback-down-line=Control+Shift+j
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+Shift+r
show-urls-launch=Control+Shift+o
show-urls-copy=Control+Shift+slash
unicode-input=none
