wallpaper {
    monitor = DP-1
    path = /home/kas/pictures/walls/lain2.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kas/pictures/walls/lain2.png
    fit_mode = cover
}

splash = false
